<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractMenu extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkMenu';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkMenu' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'descricao' => 'string',
        'url' => 'string',
        'pai' => 'integer',
        'administrador' => 'boolean',
        'master' => 'boolean',
        'gestor' => 'boolean',
        'usuario' => 'boolean',
        'icon' => 'string',
        'ordem' => 'integer'
    ];
    
    public function menu()
    {
        return $this->belongsTo('\App\Models\Menu', 'pai', 'pkMenu');
    }
    
    public function menus()
    {
        return $this->hasMany('\App\Models\Menu', 'pai', 'pkMenu');
    }
}
