<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractMateria extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkMateria';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkMateria' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'fkTema' => 'integer',
        'titulo' => 'string',
        'descricao' => 'string',
        'fkCategoria' => 'integer'
    ];
    
    public function tema()
    {
        return $this->belongsTo('\App\Models\Tema', 'fkTema', 'pkTema');
    }
    
    public function categoria()
    {
        return $this->belongsTo('\App\Models\Categoria', 'fkCategoria', 'pkCategoria');
    }
    
    public function conteudos()
    {
        return $this->hasMany('\App\Models\Item', 'fkMateria', 'pkMateria');
    }
    public function favorito()
    {
        return $this->belongsToMany('\App\Models\Favorito', 'fkMateria', 'pkMateria');
    }
}
