<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractFaleConosco extends Model
{
    /**
     * Primary key name.
     *
     * @var string
     */
    public $primaryKey = 'pkFaleConosco';

    /**
     * Primary key type.
     *
     * @var string
     */
    protected $keyType = 'bigInteger';

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'pkFaleConosco' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'mensagem' => 'string',
        'fkUsuario' => 'integer',
        'titulo' => 'string'
    ];

    public function usuario()
    {
        return $this->belongsTo('\App\Models\Usuario', 'fkUsuario', 'pkUsuario');
    }
}
