<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractTipoDeitem extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkTipoDeItem';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkTipoDeItem' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'descricao' => 'string'
    ];
    
    public function conteudos()
    {
        return $this->hasMany('\App\Models\Item', 'fkTipoDeItem', 'pkTipoDeItem');
    }
}
