<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractGestor extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'gestor';
    
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkGestor';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkGestor' => 'integer',
        'fkSetor' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'fkEmpresa' => 'integer',
        'fkUsuario' => 'integer',
        'ehmaster' => 'boolean'
    ];
    
    public function empresa()
    {
        return $this->belongsTo('\App\Models\Empresa', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function setor()
    {
        return $this->belongsTo('\App\Models\Setor', 'fkSetor', 'pkSetor');
    }
    
    public function usuario()
    {
        return $this->belongsTo('\App\Models\Usuario', 'fkUsuario', 'pkUsuario');
    }
}
