<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractAlerta extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkAlerta';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkAlerta' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'mensagem' => 'string',
        'fkSetor' => 'integer',
        'fkUsuario' => 'integer',
        'grupo' => 'integer',
        'fkEmpresa' => 'integer',
        'titulo' => 'string'
    ];
    
    public function setor()
    {
        return $this->belongsTo('\App\Models\Setor', 'fkSetor', 'pkSetor');
    }
    
    public function usuario()
    {
        return $this->belongsTo('\App\Models\Usuario', 'fkUsuario', 'pkUsuario');
    }
    
    public function empresa()
    {
        return $this->belongsTo('\App\Models\Empresa', 'fkEmpresa', 'pkEmpresa');
    }
}
