<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractRespostas extends Model
{
    /**
     * Primary key name.
     *
     * @var string
     */
    public $primaryKey = 'pkRespostas';

    /**
     * Primary key type.
     *
     * @var string
     */
    protected $keyType = 'bigInteger';

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'fkQuestoes' => 'integer',
        'pkRespostas' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'texto' => 'string',
        'correta' => 'boolean',
        'pontuacaoPorQuestao' => 'decimal:2'
    ];

    public function questoes()
    {
        return $this->belongsTo('\App\Models\Questoes', 'fkQuestoes', 'pkQuestoes');
    }


}
