<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractStatus extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
     protected $table = 'status';

    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkStatus';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkStatus' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'descricao' => 'string'
    ];
    
    public function ferias()
    {
        return $this->hasMany('\App\Models\Ferias', 'fkStatus', 'pkStatus');
    }
}
