<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractEmpresa extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'empresa';
    
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkEmpresa';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkEmpresa' => 'integer',
        'razaoSocial' => 'string',
        'nomeFantasia' => 'string',
        'cnpj' => 'string',
        'endereco' => 'string',
        'site' => 'string',
        'telefone' => 'string',
        'redeSocial' => 'string',
        'ramoDeAtividade' => 'string',
        'responsavelMarketing' => 'string',
        'responsavelFinanceiro' => 'string',
        'responsavelComercial' => 'string',
        'numero' => 'integer',
        'complemento' => 'string',
        'bairro' => 'string',
        'cidade' => 'string',
        'estado' => 'string',
        'cep' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function cargos()
    {
        return $this->hasMany('\App\Models\Cargo', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function gestors()
    {
        return $this->hasMany('\App\Models\Gestor', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function usuarios()
    {
        return $this->hasMany('\App\Models\Usuario', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function setors()
    {
        return $this->hasMany('\App\Models\Setor', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function redesSociais()
    {
        return $this->hasMany('\App\Models\RedesSociais', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function alertas()
    {
        return $this->hasMany('\App\Models\Alerta', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function categorias()
    {
        return $this->hasMany('\App\Models\Categoria', 'fkEmpresa', 'pkEmpresa');
    }
}
