<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractRedesSociais extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkRedesSociais';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkRedesSociais' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'fkUsuario' => 'integer',
        'fkTipoRedeSocial' => 'integer',
        'fkEmpresa' => 'integer'
    ];
    
    public function usuario()
    {
        return $this->belongsTo('\App\Models\Usuario', 'fkUsuario', 'pkUsuario');
    }
    
    public function tiposRedesSociais()
    {
        return $this->belongsTo('\App\Models\TiposRedesSociais', 'fkTipoRedeSocial', 'pkTiposRedesSociais');
    }
    
    public function empresa()
    {
        return $this->belongsTo('\App\Models\Empresa', 'fkEmpresa', 'pkEmpresa');
    }
}
