<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractUsuario extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'usuario';
    
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkUsuario';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkUsuario' => 'integer',
        'nome' => 'string',
        'email' => 'string',
        'cpf' => 'string',
        'telefone' => 'string',
        'urlImage' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'fkEmpresa' => 'integer',
        'fkSetor' => 'integer',
        'fkCargo' => 'integer',
        'facebook' => 'string',
        'instagram' => 'string',
        'twitter' => 'string',
        'linkedin' => 'string',
        'site' => 'string',
        'password' => 'string',
        'administrador' => 'boolean'
    ];
    
    public function empresa()
    {
        return $this->belongsTo('\App\Models\Empresa', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function setor()
    {
        return $this->belongsTo('\App\Models\Setor', 'fkSetor', 'pkSetor');
    }
    
    public function cargo()
    {
        return $this->belongsTo('\App\Models\Cargo', 'fkCargo', 'pkCargo');
    }
    
    public function gestors()
    {
        return $this->hasMany('\App\Models\Gestor', 'fkUsuario', 'pkUsuario');
    }
    
    public function redesSociais()
    {
        return $this->hasMany('\App\Models\RedesSociais', 'fkUsuario', 'pkUsuario');
    }
    
    public function alertas()
    {
        return $this->hasMany('\App\Models\Alerta', 'fkUsuario', 'pkUsuario');
    }
    
    public function respostas()
    {
        return $this->belongsToMany('\App\Models\Respostas', 'usuario_respostas', 'usuario_pk_usuario', 'respostas_pk_respostas');
    }
    public function favorito()
    {
        return $this->belongsToMany('\App\Models\Favorito', 'Favorito', 'pkUsuario');
    }
    public function ferias()
    {
        return $this->belongsTo('\App\Models\Ferias', 'fkFerias', 'pkFerias');
    }
}
