<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractFerias extends Model
{
    /**
     * Primary key name.
     *
     * @var string
     */
    protected $table = 'ferias';
    
    public $primaryKey = 'pkFerias';

    /**
     * Primary key type.
     *
     * @var string
     */
    protected $keyType = 'bigInteger';

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'pkFerias'      => 'integer',
        'fkUsuario'     => 'integer',
        'fkStatus'      => 'integer',
        'dataInico'     => 'date',
        'dataFinal'     => 'date',
        'resposta'      => 'string',
        'created_at'    => 'datetime',
        'updated_at'    => 'datetime',
    ];

    public function usuario()
    {
        return $this->belongsTo('\App\Models\Usuario', 'fkUsuario', 'pkUsuario');
    }

    public function status()
    {
        return $this->belongsTo('\App\Models\Status', 'fkStatus', 'pkStatus');
    }
}
