<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractTiposRedesSociais extends Model
{
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkTiposRedesSociais';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkTiposRedesSociais' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function redesSociais()
    {
        return $this->hasMany('\App\Models\RedesSociais', 'fkTipoRedeSocial', 'pkTiposRedesSociais');
    }
}
