<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractSetor extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'setor';
    
    /**  
     * Primary key name.
     * 
     * @var string
     */
    public $primaryKey = 'pkSetor';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'pkSetor' => 'integer',
        'nome' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'fkEmpresa' => 'integer'
    ];
    
    public function empresa()
    {
        return $this->belongsTo('\App\Models\Empresa', 'fkEmpresa', 'pkEmpresa');
    }
    
    public function gestors()
    {
        return $this->hasMany('\App\Models\Gestor', 'fkSetor', 'pkSetor');
    }
    
    public function usuarios()
    {
        return $this->hasMany('\App\Models\Usuario', 'fkSetor', 'pkSetor');
    }
    
    public function alertas()
    {
        return $this->hasMany('\App\Models\Alerta', 'fkSetor', 'pkSetor');
    }
}
